image: maven:3.6.3-jdk-11

stages:
  - analysis
  - test
  - package
  - docker
  - deploy

sonarqube-check:
  stage: analysis
  script:
    - mvn -B -q verify sonar:sonar
      -Dsonar.qualitygate.wait=true
      '-Dtest=!%regex[.*UI.*]'
  allow_failure: true
  only:
    - master

unit-test:
  stage: test
  script:
    - mvn -B test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  except:
    - merge_requests
    - master

integration-test:
  stage: test
  script:
    - mvn -B integration-test '-Dtest=!%regex[.*UI.*]'
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  only:
    - merge_requests
    - master

package:
  stage: package
  script:
    - mvn deploy -Dmaven.test.skip=true -s ci_settings.xml
  artifacts:
    paths:
      - target/rest-api-0.0.1-SNAPSHOT.jar
  only:
    - master

docker:
  stage: docker
  image: docker:stable
  only:
    - master
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  script:
    - echo "Building and uploading Docker image 🐳"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH

.deploy:
  stage: deploy
  trigger: tqs-domus/compose
  only:
    - master
